### ISSUE TITLE
Custom installation fails due to yeoman error (?)

### ISSUE THREAD

**Issue by chaenu** [Sebastian-Fitzner/generator-veams#63] opened 2016-05-04 09:35 UTC
_From @chaenu on May 3, 2016 14:42_

Hey,

there's an error when using the custom installation routine. The minimal one works fine.

Used versions:
Node.js: v6.0.0
generator-veams: 6.7.3
veams-cli: 1.2.20
inserter: 1.0.4

The error happens after selecting the js libraries (see below). Same error happens on a windows machine. 

> Custom installation routine selected.
> 
> ? Your project name test2
> ? Would you mind telling me your name? thomas
> ? Which task runner do you want to use? (Press <space> to select)Grunt
> ? Which Grunt-Plugins do you want to use? (Press <space> to select)grunt-autoprefixer, grunt-browser-sync, grunt-browserify, grunt-combine-mq, grunt-dr-svg-sprites, grunt-version
> ? Which Template Engine do you want to install? Assemble
> ? Do you want to install Assemble-Plugins? No
> ? Do you want to use Extended Layouts in Assemble? No
> ? Do you want to use any Sass Frameworks? (Press <space> to select)
> ? Do you want to use any JS Libraries? 
> ❯◉ jQuery (latest Version)
>  ◯ BackboneJS
>  ◯ Exoskeleton
>  ◯ Ampersand (can only be used with CommonJS)
>  ◯ document-register-element
> 
> /usr/local/lib/node_modules/veams-cli/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:77
>     throw e;
>     ^
> true

Any idea what's going on?

_Copied from original issue: Sebastian-Fitzner/veams-cli#4_

**Comment by chaenu** [comment] 2016-05-04 09:35
_From @Sebastian-Fitzner on May 3, 2016 18:29_

I guess it is a problem with the new node version. There are some major breaking changes, so a variety of projects needs a bit time to update the code base,

But you can test if your build is successful when using a previous node version ... 

Furthermore it is a problem of generator-veams, so it would be awesome if you can transfer the ticket over

**Comment by chaenu** [comment] 2016-05-04 09:43
I tried with v0.12.7, v5.4.0 and v6.0.0 - the error is always the same.

**Comment by Sw0rdiX** [comment] 2016-05-04 14:35
Hi, 

i check this with different version setups and found out that this issue is caused by yeoman-environment. all version of yeoman-enviroment from 1.6.0+ does not work. (last working version for me 1.5.3).

Greetz,
Sw0rdiX

**Comment by Sebastian-Fitzner** [comment] 2016-05-04 17:07
Thx for your effort ... I researched a bit too and the issue is caused by inquirer.js in the Major version 1.x ... 

Will fix is asap.

**Comment by Sebastian-Fitzner** [comment] 2016-05-04 17:51
Issue temporary fixed in v1.2.21 of veams-cli. We need some time to rewrite our validate functions with promises instead of callbacks, see https://github.com/SBoudrias/Inquirer.js/releases/tag/v1.0.0

**Comment by rayphi** [comment] 2017-02-04 20:47
Is this fixed?
I ran into the same error with following setup:
node: v6.9.5
yo: 1.8.5
generator-veams: 7.6.1

**Comment by Sebastian-Fitzner** [comment] 2017-02-05 12:06
If you use the Veams-Cli you won't have any problems at all otherwise you probably have some issues. 

I will start rewriting the generator in the next few days. So if you want to use yo with generator-veams you have to wait a few days ...

**Comment by Sebastian-Fitzner** [comment] 2017-02-18 18:21
@rayphi Okay I am almost done with the new version. I will publish the new one in the next few days. Then you can use it with newest yo version.

**Comment by Sebastian-Fitzner** [comment] 2017-02-26 23:28
@rayphi : Newest version is available and issue is fixed! Have fun ...

**Closed by Sebastian-Fitzner** 2017-02-26 23:28 UTC
